Traceback (most recent call last):
  File "/home/aim/anaconda3/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/aim/anaconda3/lib/python3.12/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aim/anaconda3/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aim/anaconda3/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/aim/anaconda3/lib/python3.12/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/aim/anaconda3/lib/python3.12/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/aim/anaconda3/lib/python3.12/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import torch
torch.manual_seed(47)

a = torch.randn(3, 1)  
b = torch.randn(2, 1)  
zX = torch.randn(3, 2, requires_grad=True) 

def grad_f(X, a, b):
    f = a.T @ X @ b 
    f.backward()  
    return X.grad

calculated_grad_X = grad_f(X, a, b)
expected_grad_X = a @ b.T
assert torch.allclose(expected_grad_X, calculated_grad_X)
print(calculated_grad_X)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[5], line 13[0m
[1;32m     10[0m     f[38;5;241m.[39mbackward()  
[1;32m     11[0m     [38;5;28;01mreturn[39;00m X[38;5;241m.[39mgrad
[0;32m---> 13[0m calculated_grad_X [38;5;241m=[39m grad_f([43mX[49m, a, b)
[1;32m     14[0m expected_grad_X [38;5;241m=[39m a [38;5;241m@[39m b[38;5;241m.[39mT
[1;32m     15[0m [38;5;28;01massert[39;00m torch[38;5;241m.[39mallclose(expected_grad_X, calculated_grad_X)

[0;31mNameError[0m: name 'X' is not defined

